services:
    spoticar-watcher:
        build: .
        container_name: spoticar-watcher
        volumes:
            - ./data:/app/data
            - ./spoticar_watch.php:/app/spoticar_watch.php
        environment:
            TZ: Europe/Paris
